# Generated by Django 2.2.4 on 2021-08-16 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedschool',
            name='comment',
            field=models.CharField(default='Add A Comment About Your Application', max_length=50),
        ),
    ]
